const IMOVEIS = [
  {
    slug: "predio-lupicinio",
    tipoFiltro: "comercial",
    tipo: "Prédio comercial",
    operacao: "Venda",
    titulo: "Prédio comercial na Avenida Lupicínio Rodrigues",
    bairro: "Santa Rita",
    cidade: "Guaíba/RS",
    endereco: "Avenida Lupicínio Rodrigues, Santa Rita, Guaíba/RS",
    preco: "R$ 290.000,00",
    area: "84m²",
    dormitorios: "",
    banheiros: "",
    vagas: "1",
    codigo: "612781010-8",
    chamada:
      "Ponto comercial em localização estratégica, ideal para quem busca visibilidade e potencial de valorização.",
    descricao: [
      "Imóvel comercial localizado em uma das vias de grande circulação da região.",
      "Boa opção para loja, escritório, atendimento profissional ou investimento.",
      "Indicado para quem procura um endereço funcional em Guaíba.",
    ],
    fotos: [
      "https://cdn.gryphtech.com/userimages/61/LargeWM/L_81b71404-c24b-41c0-9143-0a0d0e15117a.jpg",
      "https://cdn.gryphtech.com/userimages/61/LargeWM/L_abf7ace3-25c6-4664-93f9-db95298e8686.jpg",
      "https://cdn.gryphtech.com/userimages/61/LargeWM/L_573b13c4-70ce-427e-a671-d2479d017bd1.jpg",
      "https://cdn.gryphtech.com/userimages/61/LargeWM/L_316b6349-da7c-4202-b3b5-0d95ba1726e0.jpg",
      "https://cdn.gryphtech.com/userimages/61/LargeWM/L_68bb6ed2-14a6-4af2-871c-e69f293f481d.jpg",
      "https://cdn.gryphtech.com/userimages/61/LargeWM/L_84518f82-5062-49f8-91ca-59a0532c4f34.jpg",
    ],
    pagina: "imoveis/predio-lupicinio.html",
  },
  {
    slug: "casa-santa-rita",
    tipoFiltro: "casa",
    tipo: "Casa",
    operacao: "Venda",
    titulo: "Casa pronta no bairro Santa Rita",
    bairro: "Santa Rita",
    cidade: "Guaíba/RS",
    endereco: "Rua Maceió, Santa Rita, Guaíba/RS",
    preco: "R$ 320.000,00",
    area: "150m²",
    dormitorios: "3",
    banheiros: "1",
    vagas: "2",
    codigo: "612781010-11",
    chamada:
      "Casa bem localizada, com excelente potencial para quem busca morar em uma região prática de Guaíba.",
    descricao: [
      "Casa situada no bairro Santa Rita, próxima a pontos importantes da região.",
      "Boa distribuição interna, com dormitórios, vaga e área adequada para a rotina familiar.",
      "Opção interessante para quem procura imóvel pronto em Guaíba.",
    ],
    fotos: [
      "https://cdn.gryphtech.com/userimages/61/LargeWM/L_abf7ace3-25c6-4664-93f9-db95298e8686.jpg",
    ],
    pagina: "imoveis/casa-santa-rita.html",
  },
  {
    slug: "terreno-pedras-brancas",
    tipoFiltro: "terreno",
    tipo: "Terreno",
    operacao: "Venda",
    titulo: "Terreno à venda em Pedras Brancas",
    bairro: "Pedras Brancas",
    cidade: "Guaíba/RS",
    endereco: "Rua Nove, Pedras Brancas, Guaíba/RS",
    preco: "R$ 86.982,00",
    area: "500m²",
    dormitorios: "",
    banheiros: "",
    vagas: "",
    codigo: "612781010-31",
    chamada:
      "Terreno amplo, plano e com potencial para construção ou investimento.",
    descricao: [
      "Terreno com 500m² em localização com potencial de valorização.",
      "Indicado para construção residencial, projeto misto ou investimento futuro.",
      "Boa oportunidade para quem deseja construir em uma região em desenvolvimento.",
    ],
    fotos: [
      "https://cdn.gryphtech.com/userimages/61/LargeWM/L_b0c41e75-8c8c-4573-9bdd-56ef3c56e9e4.jpg",
    ],
    pagina: "imoveis/terreno-pedras-brancas.html",
  },
  {
    slug: "casa-colina",
    tipoFiltro: "casa",
    tipo: "Casa",
    operacao: "Venda",
    titulo: "Casa no bairro Colina",
    bairro: "Colina",
    cidade: "Guaíba/RS",
    endereco: "Rua Belmiro Andriotti, Colina, Guaíba/RS",
    preco: "R$ 295.000,00",
    area: "117m²",
    dormitorios: "2",
    banheiros: "",
    vagas: "2",
    codigo: "612781010-33",
    chamada:
      "Casa confortável no bairro Colina, ideal para quem busca praticidade e bom custo-benefício.",
    descricao: [
      "Imóvel residencial localizado no bairro Colina, em Guaíba.",
      "Conta com 117m² e dois dormitórios, sendo uma opção interessante para moradia.",
      "Boa alternativa para famílias ou compradores que desejam sair do aluguel.",
    ],
    fotos: [],
    pagina: "imoveis/casa-colina.html",
  },
];
