const IMOVEIS = [
  {
    slug: "terreno-pedras-brancas-jose-carlos",
    tipoFiltro: "terreno",
    tipo: "Terreno",
    operacao: "Venda",
    titulo: "Terreno em Pedras Brancas",
    bairro: "Pedras Brancas",
    cidade: "Guaíba/RS",
    endereco: "Estrada Doutor José Carlos Ferreira, Pedras Brancas, Guaíba/RS",
    preco: "R$ 180.000,00",
    area: "400m²",
    dormitorios: "",
    banheiros: "",
    vagas: "",
    codigo: "612781010-30",
    chamada:
      "Terreno com 400m² em Pedras Brancas, ideal para construir ou investir em uma região com potencial de valorização.",
    descricao: [
      "Terreno localizado em Pedras Brancas, região em desenvolvimento em Guaíba.",
      "Boa opção para quem busca espaço para construir com liberdade de projeto.",
      "Indicado para moradia, investimento ou futura valorização patrimonial.",
    ],
    fotos: [],
    pagina: "imoveis/terreno-pedras-brancas-jose-carlos.html",
  },
  {
    slug: "casa-bom-fim",
    tipoFiltro: "casa",
    tipo: "Casa",
    operacao: "Venda",
    titulo: "Casa no bairro Bom Fim",
    bairro: "Bom Fim",
    cidade: "Guaíba/RS",
    endereco: "Rua Pedro Caldas, Bom Fim, Guaíba/RS",
    preco: "R$ 180.000,00",
    area: "70m²",
    dormitorios: "3",
    banheiros: "1",
    vagas: "",
    codigo: "612781010-32",
    chamada:
      "Casa desocupada, pronta para uso e com terreno amplo no bairro Bom Fim.",
    descricao: [
      "Ótima casa no bairro Bom Fim, em uma região tranquila e de fácil acesso.",
      "Possui 3 quartos, 1 banheiro, cozinha ampla e sala de estar.",
      "O terreno possui 300m², oferecendo possibilidade de ampliação, paisagismo ou melhor aproveitamento externo.",
      "Imóvel indicado para quem busca uma casa acessível, funcional e pronta para morar.",
    ],
    fotos: [],
    pagina: "imoveis/casa-bom-fim.html",
  },
  {
    slug: "terreno-pedras-brancas-rua-nove",
    tipoFiltro: "terreno",
    tipo: "Terreno",
    operacao: "Venda",
    titulo: "Terreno à venda em Pedras Brancas",
    bairro: "Pedras Brancas",
    cidade: "Guaíba/RS",
    endereco: "Rua Nove, Pedras Brancas, Guaíba/RS",
    preco: "R$ 86.982,00",
    area: "500m²",
    dormitorios: "",
    banheiros: "",
    vagas: "",
    codigo: "612781010-31",
    chamada: "Terreno amplo de 500m², ideal para construção ou investimento.",
    descricao: [
      "Terreno com 500m² em localização estratégica em Pedras Brancas.",
      "Boa alternativa para quem deseja construir um imóvel sob medida.",
      "Indicado para investimento, moradia futura ou projeto residencial.",
    ],
    fotos: [
      "https://cdn.gryphtech.com/userimages/61/LargeWM/L_b0c41e75-8c8c-4573-9bdd-56ef3c56e9e4.jpg",
    ],
    pagina: "imoveis/terreno-pedras-brancas-rua-nove.html",
  },
  {
    slug: "sobrado-santa-rita",
    tipoFiltro: "sobrado",
    tipo: "Sobrado",
    operacao: "Venda",
    titulo: "Sobrado com perfil de investimento na Santa Rita",
    bairro: "Santa Rita",
    cidade: "Guaíba/RS",
    endereco: "Av. Osvaldo Jardim, Santa Rita, Guaíba/RS",
    preco: "R$ 1.100.000,00",
    area: "500m²",
    dormitorios: "5",
    banheiros: "7",
    vagas: "4",
    codigo: "612781010-28",
    chamada: "Imóvel multifuncional com perfil de renda, próximo à BR-116.",
    descricao: [
      "Imóvel misto localizado no bairro Santa Rita, em posição estratégica e com grande potencial comercial.",
      "O conjunto possui lojas comerciais e unidades residenciais, sendo uma oportunidade para investidores.",
      "Segundo a descrição do anúncio, o imóvel está aproximadamente 80% locado, gerando renda mensal estimada em torno de R$ 5.000,00.",
      "Excelente opção para quem busca diversificação de renda, localização forte e valorização patrimonial.",
    ],
    fotos: [],
    pagina: "imoveis/sobrado-santa-rita.html",
  },
  {
    slug: "casa-santa-rita",
    tipoFiltro: "casa",
    tipo: "Casa",
    operacao: "Venda",
    titulo: "Casa pronta no bairro Santa Rita",
    bairro: "Santa Rita",
    cidade: "Guaíba/RS",
    endereco: "Rua Maceió, nº 855, Santa Rita, Guaíba/RS",
    preco: "R$ 320.000,00",
    area: "150m²",
    dormitorios: "3",
    banheiros: "1",
    vagas: "2",
    codigo: "612781010-11",
    chamada:
      "Casa pronta na Santa Rita, ideal para quem busca praticidade e boa localização.",
    descricao: [
      "Casa localizada na Rua Maceió, no bairro Santa Rita, próxima ao Supermercado Atual.",
      "Possui 150m², 3 dormitórios, 1 banheiro e 2 vagas.",
      "Boa opção para famílias que buscam imóvel pronto em uma região prática de Guaíba.",
    ],
    fotos: [],
    pagina: "imoveis/casa-santa-rita.html",
  },
  {
    slug: "terreno-colina-lorival",
    tipoFiltro: "terreno",
    tipo: "Terreno",
    operacao: "Venda",
    titulo: "Área ampla no bairro Colina",
    bairro: "Colina",
    cidade: "Guaíba/RS",
    endereco: "Av. Lorival Luiz da Cunha, Colina, Guaíba/RS",
    preco: "R$ 285.000,00",
    area: "4.630m²",
    dormitorios: "",
    banheiros: "",
    vagas: "",
    codigo: "612781010-15",
    chamada:
      "Área ampla com 4.630m² no bairro Colina, excelente para investimento ou projeto especial.",
    descricao: [
      "Terreno amplo localizado no bairro Colina.",
      "Com metragem expressiva de 4.630m², oferece diversas possibilidades de aproveitamento.",
      "Boa opção para quem procura área maior em Guaíba com potencial de valorização.",
    ],
    fotos: [],
    pagina: "imoveis/terreno-colina-lorival.html",
  },
  {
    slug: "casa-colina",
    tipoFiltro: "casa",
    tipo: "Casa",
    operacao: "Venda",
    titulo: "Casa no bairro Colina",
    bairro: "Colina",
    cidade: "Guaíba/RS",
    endereco: "Rua Belmiro Andriotti, Colina, Guaíba/RS",
    preco: "R$ 295.000,00",
    area: "117m²",
    dormitorios: "2",
    banheiros: "2",
    vagas: "",
    codigo: "612781010-33",
    chamada:
      "Casa confortável no bairro Colina, com 2 dormitórios e 2 banheiros.",
    descricao: [
      "Casa localizada na Rua Belmiro Andriotti, no bairro Colina.",
      "Possui 117m², 2 dormitórios e 2 banheiros.",
      "Imóvel indicado para quem busca conforto, praticidade e bom custo-benefício em Guaíba.",
    ],
    fotos: [],
    pagina: "imoveis/casa-colina.html",
  },
  {
    slug: "predio-lupicinio",
    tipoFiltro: "comercial",
    tipo: "Prédio comercial",
    operacao: "Venda",
    titulo: "Prédio comercial na Avenida Lupicínio Rodrigues",
    bairro: "Santa Rita",
    cidade: "Guaíba/RS",
    endereco: "Avenida Lupicínio Rodrigues, Santa Rita, Guaíba/RS",
    preco: "R$ 290.000,00",
    area: "84m²",
    dormitorios: "",
    banheiros: "",
    vagas: "1",
    codigo: "612781010-8",
    chamada:
      "Prédio comercial em localização estratégica, ideal para negócio próprio ou investimento.",
    descricao: [
      "Imóvel comercial localizado na Avenida Lupicínio Rodrigues, no bairro Santa Rita.",
      "Conta com 84m² e 1 vaga.",
      "Boa opção para loja, escritório, atendimento profissional ou investimento comercial.",
    ],
    fotos: [
      "https://cdn.gryphtech.com/userimages/61/LargeWM/L_81b71404-c24b-41c0-9143-0a0d0e15117a.jpg",
      "https://cdn.gryphtech.com/userimages/61/LargeWM/L_abf7ace3-25c6-4664-93f9-db95298e8686.jpg",
      "https://cdn.gryphtech.com/userimages/61/LargeWM/L_573b13c4-70ce-427e-a671-d2479d017bd1.jpg",
      "https://cdn.gryphtech.com/userimages/61/LargeWM/L_316b6349-da7c-4202-b3b5-0d95ba1726e0.jpg",
      "https://cdn.gryphtech.com/userimages/61/LargeWM/L_68bb6ed2-14a6-4af2-871c-e69f293f481d.jpg",
      "https://cdn.gryphtech.com/userimages/61/LargeWM/L_84518f82-5062-49f8-91ca-59a0532c4f34.jpg",
    ],
    pagina: "imoveis/predio-lupicinio.html",
  },
  {
    slug: "casa-coronel-nassuca",
    tipoFiltro: "casa",
    tipo: "Casa",
    operacao: "Venda",
    titulo: "Casa no bairro Coronel Nassuca",
    bairro: "Coronel Nassuca",
    cidade: "Guaíba/RS",
    endereco: "Rua Maneca Paiva, 144, Coronel Nassuca, Guaíba/RS",
    preco: "R$ 250.000,00",
    area: "306m²",
    dormitorios: "1",
    banheiros: "2",
    vagas: "",
    codigo: "612781010-16",
    chamada:
      "Casa com terreno de 306m², boa localização e potencial de valorização.",
    descricao: [
      "Casa localizada na Rua Maneca Paiva, no bairro Coronel Nassuca.",
      "O imóvel possui área total de 306m², 1 dormitório e 2 banheiros.",
      "A página do imóvel informa área útil de 70m² e construção de 2003.",
      "Boa alternativa para moradia, reforma, ampliação ou investimento em uma região residencial.",
    ],
    fotos: [],
    pagina: "imoveis/casa-coronel-nassuca.html",
  },
  {
    slug: "casa-jardim-dos-lagos",
    tipoFiltro: "casa",
    tipo: "Casa",
    operacao: "Venda",
    titulo: "Casa no Jardim dos Lagos",
    bairro: "Jardim dos Lagos",
    cidade: "Guaíba/RS",
    endereco: "Rua Noel Guarani, Jardim dos Lagos, Guaíba/RS",
    preco: "R$ 370.000,00",
    area: "108m²",
    dormitorios: "3",
    banheiros: "1",
    vagas: "",
    codigo: "612781010-21",
    chamada: "Casa com 108m² no Jardim dos Lagos, com 3 dormitórios.",
    descricao: [
      "Casa localizada na Rua Noel Guarani, no bairro Jardim dos Lagos.",
      "Possui 108m², 3 dormitórios e 1 banheiro.",
      "Opção interessante para famílias que buscam imóvel residencial em Guaíba.",
    ],
    fotos: [],
    pagina: "imoveis/casa-jardim-dos-lagos.html",
  },
  {
    slug: "terreno-br116-bom-fim",
    tipoFiltro: "terreno",
    tipo: "Terreno",
    operacao: "Venda",
    titulo: "Terreno próximo à BR-116",
    bairro: "Pedra Brancas",
    cidade: "Guaíba/RS",
    endereco: "Rua Est. BR-116, Bairro Bom Fim, Guaíba/RS",
    preco: "R$ 94.453,00",
    area: "165m²",
    dormitorios: "",
    banheiros: "",
    vagas: "",
    codigo: "612781010-19",
    chamada: "Terreno de 165m² em localização estratégica, próximo à BR-116.",
    descricao: [
      "Terreno localizado na região de Pedra Brancas, próximo à BR-116 e ao bairro Bom Fim.",
      "Possui 165m² e valor acessível para investimento.",
      "Boa opção para quem busca terreno compacto em ponto estratégico de Guaíba.",
    ],
    fotos: [],
    pagina: "imoveis/terreno-br116-bom-fim.html",
  },
];
